import React from 'react'

HAHA.propTypes = {}

const dataTest = [
    {
        encodeId: 'IWZ9Z09E',
        cover: 'https://photo-zmp3.zadn.vn/cover/5/7/d/b/57dbc9145318876d3d79e26a99ec8a83.jpg',
        thumbnail: 'https://photo-zmp3.zadn.vn/cover/0/a/e/f/0aef849d584c7e995073617f53b9ac24.jpg',
        thumbnailHasText: 'https://photo-zmp3.zadn.vn/cover/9/8/7/3/98732de40faf3fa472968bd081369978.jpg',
        thumbnailR: 'https://photo-zmp3.zadn.vn/cover/a/2/3/b/a23b64ffea1892027878ffe3fd5a38bb.jpg',
        title: 'Tình Yêu',
        link: '/hub/Tinh-Yeu/IWZ9Z09E.html',
        description: '',
        playlists: [
            {
                encodeId: '6ZWZD88D',
                title: 'Một Tình Yêu Siêu Khủng Long',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/a/3/e/9/a3e994d71dbddf26dba54cd92bd746a2.jpg',
                isoffical: true,
                link: '/album/Mot-Tinh-Yeu-Sieu-Khung-Long-Various-Artists/6ZWZD88D.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 435,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/a/3/e/9/a3e994d71dbddf26dba54cd92bd746a2.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: '6I07OWOA',
                title: 'Anh Thương Em Nhất Mà',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/c/c/7/b/cc7ba4ee3517cf674d0bf1b9aba27299.jpg',
                isoffical: true,
                link: '/album/Anh-Thuong-Em-Nhat-Ma-Various-Artists/6I07OWOA.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 422,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/c/c/7/b/cc7ba4ee3517cf674d0bf1b9aba27299.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: '6II7IUIU',
                title: 'Yêu Thì Yêu, Không Yêu Thì Yêu',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/6/5/2/9/652992cda94f5ea61eb8b15a9f4044ac.jpg',
                isoffical: true,
                link: '/album/Yeu-Thi-Yeu-Khong-Yeu-Thi-Yeu-Various-Artists/6II7IUIU.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 435,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/6/5/2/9/652992cda94f5ea61eb8b15a9f4044ac.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
        ],
    },
    {
        encodeId: 'IWZ9Z098',
        cover: 'https://photo-zmp3.zadn.vn/cover/7/b/a/3/7ba3b164504295c3ab8ee10e1133678e.jpg',
        thumbnail: 'https://photo-zmp3.zadn.vn/cover/e/3/d/4/e3d43659c6dc756f87f4e44220313f92.jpg',
        thumbnailHasText: 'https://photo-zmp3.zadn.vn/cover/d/0/7/1/d0714f6cfd28af5d7518d582285f3312.jpg',
        thumbnailR: 'https://photo-zmp3.zadn.vn/cover/a/5/9/2/a592ccc7e41403e2f7b5233e064cf594.jpg',
        title: 'Du lịch',
        link: '/hub/Du-lich/IWZ9Z098.html',
        description: '',
        playlists: [
            {
                encodeId: 'ZAFAWWE0',
                title: 'Nào Ta Cùng Phượt!',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/4/7/9/2/4792b040f5120e1830b68a3a5b90a7a5.jpg',
                isoffical: true,
                link: '/album/Nao-Ta-Cung-Phuot-Various-Artists/ZAFAWWE0.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 422,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/4/7/9/2/4792b040f5120e1830b68a3a5b90a7a5.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZU6BFA7F',
                title: 'Phượt Cùng Rap Việt',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/a/8/9/b/a89bd78bbafed6c7d0bd1d6ac491423f.jpg',
                isoffical: true,
                link: '/album/Phuot-Cung-Rap-Viet-Various-Artists/ZU6BFA7F.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 298,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/a/8/9/b/a89bd78bbafed6c7d0bd1d6ac491423f.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZOZ0CUUC',
                title: 'Những Chuyến Xe Dài',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/0/0/1/4/00142fcd783e08da147fdc6a041a5e86.jpg',
                isoffical: true,
                link: '/album/Nhung-Chuyen-Xe-Dai-Various-Artists/ZOZ0CUUC.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 88,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/0/0/1/4/00142fcd783e08da147fdc6a041a5e86.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
        ],
    },
    {
        encodeId: 'IWZ9Z09Z',
        cover: 'https://photo-zmp3.zadn.vn/cover/9/5/3/4/9534e6652f113fc11d79247f5cdd69dd.jpg',
        thumbnail: 'https://photo-zmp3.zadn.vn/cover/b/b/b/0/bbb0a8963e9ed3b81974613b52b9476c.jpg',
        thumbnailHasText: 'https://photo-zmp3.zadn.vn/cover/9/2/d/5/92d59a48d9df9e94275b30a0718d5121.jpg',
        thumbnailR: 'https://photo-zmp3.zadn.vn/cover/c/7/4/2/c74237632003d926a857cce6cbd11b83.jpg',
        title: 'Cà Phê',
        link: '/hub/Ca-Phe/IWZ9Z09Z.html',
        description: '',
        playlists: [
            {
                encodeId: '60B8ZUU9',
                title: 'Coffee 50: Zing Choice',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/f/0/f/e/f0fe6ab39be2c7d81dbc4452201ed500.jpg',
                isoffical: true,
                link: '/album/Coffee-50-Zing-Choice-Various-Artists/60B8ZUU9.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 422,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/f/0/f/e/f0fe6ab39be2c7d81dbc4452201ed500.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: '60B8UOEA',
                title: 'Coffeehouse Country',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/2/0/3/b/203be92c8207d04f7ec3494a74cea7f4.jpg',
                isoffical: true,
                link: '/album/Coffeehouse-Country-Various-Artists/60B8UOEA.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 422,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/2/0/3/b/203be92c8207d04f7ec3494a74cea7f4.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: '60B9UW9Z',
                title: 'Coffeehouse Bene',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/3/e/6/6/3e6621faf08533263ecf8333ff15dc70.jpg',
                isoffical: true,
                link: '/album/Coffeehouse-Bene-Various-Artists/60B9UW9Z.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 322,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/3/e/6/6/3e6621faf08533263ecf8333ff15dc70.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
        ],
    },
    {
        encodeId: 'IWZ9Z097',
        cover: 'https://photo-zmp3.zadn.vn/cover/9/2/4/d/924d799e99bc603fe8aab02284711de1.jpg',
        thumbnail: 'https://photo-zmp3.zadn.vn/cover/4/d/f/4/4df44f0a15edb254717c383cf256b193.jpg',
        thumbnailHasText: 'https://photo-zmp3.zadn.vn/cover/c/1/5/1/c151d0ea45ca4e88bade5841047acb9e.jpg',
        thumbnailR: 'https://photo-zmp3.zadn.vn/cover/2/5/2/9/25296c695110c33adaf08901c9223017.jpg',
        title: 'Chơi Game',
        link: '/hub/Choi-Game/IWZ9Z097.html',
        description: '',
        playlists: [
            {
                encodeId: 'ZOB0U7O9',
                title: 'Thắng Combat - Đánh Bại Kẻ Địch',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/1/1/c/1/11c1559f9a90043845400df3761c8981.jpg',
                isoffical: true,
                link: '/album/Thang-Combat-Danh-Bai-Ke-Dich-Various-Artists/ZOB0U7O9.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 298,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/1/1/c/1/11c1559f9a90043845400df3761c8981.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZOUZC8FW',
                title: 'K-POP Dance Gaming',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/a/5/f/6/a5f64c0739b363f13d5cf92e4f2bcf03.jpg',
                isoffical: true,
                link: '/album/K-POP-Dance-Gaming-Various-Artists/ZOUZC8FW.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 235,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/a/5/f/6/a5f64c0739b363f13d5cf92e4f2bcf03.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZOAEEDCB',
                title: 'Nhạc Dành Cho Game Thủ Liên Minh',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/9/1/8/1/91818264628bd96311ac1831ec1af14e.jpg',
                isoffical: true,
                link: '/album/Nhac-Danh-Cho-Game-Thu-Lien-Minh-League-Of-Legends/ZOAEEDCB.html',
                isIndie: false,
                PR: false,
                artists: [
                    {
                        id: 'IW6W7CU9',
                        name: 'League Of Legends',
                        link: '/nghe-si/League-Of-Legends',
                        spotlight: false,
                        playlistId: 'Z6BUIZFI',
                    },
                ],
                artistsNames: 'League Of Legends',
                playItemMode: 0,
                subType: 1,
                uid: 298,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/9/1/8/1/91818264628bd96311ac1831ec1af14e.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
        ],
    },
    {
        encodeId: 'IWZ9Z09D',
        cover: 'https://photo-zmp3.zadn.vn/cover/7/f/3/2/7f3211c85f057eaf1adfc4debad997d7.jpg',
        thumbnail: 'https://photo-zmp3.zadn.vn/cover/8/0/4/7/8047a5134646835763068f7439e17f2b.jpg',
        thumbnailHasText: 'https://photo-zmp3.zadn.vn/cover/b/8/2/1/b8212d0524ead535a238c624ab9649e2.jpg',
        thumbnailR: 'https://photo-zmp3.zadn.vn/cover/c/8/4/9/c849dda54d0c4db98486fd33d9b1d5ad.jpg',
        title: 'Tiệc Tùng',
        link: '/hub/Tiec-Tung/IWZ9Z09D.html',
        description: '',
        playlists: [
            {
                encodeId: 'ZOUU700I',
                title: 'Dance All Night',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/5/5/a/5/55a5f8be0f086195c95b1b99968bf317.jpg',
                isoffical: true,
                link: '/album/Dance-All-Night-Various-Artists/ZOUU700I.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 235,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/5/5/a/5/55a5f8be0f086195c95b1b99968bf317.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZWZCI8U9',
                title: 'We Are Young',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/0/6/0/d/060d24699dcd3c97a125435bdbb04172.jpg',
                isoffical: true,
                link: '/album/We-Are-Young-Various-Artists/ZWZCI8U9.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 0,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/0/6/0/d/060d24699dcd3c97a125435bdbb04172.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZOUU77D7',
                title: "Can't Stop The Party!",
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/0/2/b/2/02b24e7c08d0c5b46999717adaf6b3f3.jpg',
                isoffical: true,
                link: '/album/Can-t-Stop-The-Party-Various-Artists/ZOUU77D7.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 234,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/0/2/b/2/02b24e7c08d0c5b46999717adaf6b3f3.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
        ],
    },
    {
        encodeId: 'IWZ9Z0AF',
        cover: 'https://photo-zmp3.zadn.vn/cover/1/6/6/4/16643b9766c7cd5a5eb819d8160eb8b8.jpg',
        thumbnail: 'https://photo-zmp3.zadn.vn/cover/2/e/9/6/2e966bf47b1989fdff7149c7a1b0f25e.jpg',
        thumbnailHasText: 'https://photo-zmp3.zadn.vn/cover/b/e/9/b/be9b83fdbb931eaf0a0342914cb6a12d.jpg',
        thumbnailR: 'https://photo-zmp3.zadn.vn/cover/0/c/6/a/0c6a98b09036e57ecea05f0d19fe7011.jpg',
        title: 'Driving',
        link: '/hub/Driving/IWZ9Z0AF.html',
        description: '',
        playlists: [
            {
                encodeId: 'ZOCIB0Z9',
                title: 'Songs To Sing In The Car',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/e/4/1/1/e411213674272c05d422cf44e1e5bcd0.jpg',
                isoffical: true,
                link: '/album/Songs-To-Sing-In-The-Car-Various-Artists/ZOCIB0Z9.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 309,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/e/4/1/1/e411213674272c05d422cf44e1e5bcd0.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: '60EUC8BC',
                title: 'Happy Drive',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/4/8/5/1/4851f489f9a09656c8f9c68fb9f4de5e.jpg',
                isoffical: true,
                link: '/album/Happy-Drive-Various-Artists/60EUC8BC.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 422,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/4/8/5/1/4851f489f9a09656c8f9c68fb9f4de5e.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: '60FZ8FOU',
                title: '90s Road Trip',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/e/6/f/2/e6f25dc2bc1fcb0b36d9a0a1d13a9f94.jpg',
                isoffical: true,
                link: '/album/90s-Road-Trip-Various-Artists/60FZ8FOU.html',
                isIndie: false,
                PR: false,
                playItemMode: 2,
                subType: 1,
                uid: 422,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/e/6/f/2/e6f25dc2bc1fcb0b36d9a0a1d13a9f94.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
        ],
    },
    {
        encodeId: 'IWZ9Z09A',
        cover: 'https://photo-zmp3.zadn.vn/cover/3/5/a/0/35a00836fa2d4f688246cbc717d30269.jpg',
        thumbnail: 'https://photo-zmp3.zadn.vn/cover/0/9/0/9/09090b19d3417d364547db3027d141d5.jpg',
        thumbnailHasText: 'https://photo-zmp3.zadn.vn/cover/0/4/6/c/046cb712123452d99e0f5d6d3f77d6ec.jpg',
        thumbnailR: 'https://photo-zmp3.zadn.vn/cover/8/5/2/c/852c3ed184696671fc596d96952ced37.jpg',
        title: 'Khúc Nhạc Vui',
        link: '/hub/Khuc-Nhac-Vui/IWZ9Z09A.html',
        description: '',
        playlists: [
            {
                encodeId: 'ZOED000C',
                title: 'Những Giai Điệu V-Pop Tươi Vui',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/7/8/8/3/788304c4c906ca801d1bf77b1f2b443f.jpg',
                isoffical: true,
                link: '/album/Nhung-Giai-Dieu-V-Pop-Tuoi-Vui-Various-Artists/ZOED000C.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 298,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/7/8/8/3/788304c4c906ca801d1bf77b1f2b443f.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZWZC0FO9',
                title: 'Khởi Động Ngày Mới',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/f/c/9/0/fc9021c3a92b3cc2fcb02ce569867ead.jpg',
                isoffical: true,
                link: '/album/Khoi-Dong-Ngay-Moi-Various-Artists/ZWZC0FO9.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 0,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/f/c/9/0/fc9021c3a92b3cc2fcb02ce569867ead.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZWZCWUAD',
                title: 'Wonderful Day',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/1/3/d/1/13d18d7e7b76da88b4e44f527a6a78eb.jpg',
                isoffical: true,
                link: '/album/Wonderful-Day-Various-Artists/ZWZCWUAD.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 0,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/1/3/d/1/13d18d7e7b76da88b4e44f527a6a78eb.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
        ],
    },
    {
        encodeId: 'IWZ9Z0C8',
        cover: 'https://photo-zmp3.zadn.vn/cover/2/8/2/a/282a894be5043c1b47446fff0d748fcb.jpg',
        thumbnail: 'https://photo-zmp3.zadn.vn/cover/1/c/c/8/1cc8ae9704ae8fb7e34487ce744083a9.jpg',
        thumbnailHasText: 'https://photo-zmp3.zadn.vn/cover/1/a/9/9/1a99f9d8d8c5563e3893d9f10cd8689a.jpg',
        thumbnailR: 'https://photo-zmp3.zadn.vn/cover/f/6/6/3/f6639d240726fcbe9c4fe584ee5cedc6.jpg',
        title: 'Dinner',
        link: '/hub/Dinner/IWZ9Z0C8.html',
        description: '',
        playlists: [
            {
                encodeId: 'ZU8ZZ8AW',
                title: 'Pizza Party',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/c/e/6/e/ce6efffbcab02ce84c820d55f4f4a9e6.jpg',
                isoffical: true,
                link: '/album/Pizza-Party-Various-Artists/ZU8ZZ8AW.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 298,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/c/e/6/e/ce6efffbcab02ce84c820d55f4f4a9e6.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZOB8UU7Z',
                title: 'Ăn Tối Một Mình',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/b/3/3/0/b3300f06b724fc8829efdacda5caabf2.jpg',
                isoffical: true,
                link: '/album/An-Toi-Mot-Minh-Various-Artists/ZOB8UU7Z.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 283,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/b/3/3/0/b3300f06b724fc8829efdacda5caabf2.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZOUOF06B',
                title: 'Dinner Chill',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/e/e/9/b/ee9b0ecc20efff5365c6751915af1209.jpg',
                isoffical: true,
                link: '/album/Dinner-Chill-Various-Artists/ZOUOF06B.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 234,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/e/e/9/b/ee9b0ecc20efff5365c6751915af1209.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
        ],
    },
    {
        encodeId: 'IWZ9Z09F',
        cover: 'https://photo-zmp3.zadn.vn/cover/7/1/a/b/71ab8a69d1ad4cad8c6289a346773073.jpg',
        thumbnail: 'https://photo-zmp3.zadn.vn/cover/d/b/5/c/db5cf069b328c7858b2d9642cc6b4529.jpg',
        thumbnailHasText: 'https://photo-zmp3.zadn.vn/cover/6/a/9/8/6a982b0ea4de24100388beb27087d241.jpg',
        thumbnailR: 'https://photo-zmp3.zadn.vn/cover/a/a/6/a/aa6afa7fdab849574a71dec0770a4b22.jpg',
        title: 'Workout',
        link: '/hub/Workout/IWZ9Z09F.html',
        description: '',
        playlists: [
            {
                encodeId: 'ZFAI06CC',
                title: 'Workout',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/2/4/e/8/24e8f9b6a7dd0013bb5edfe3a0efb30e.jpg',
                isoffical: true,
                link: '/album/Workout-Various-Artists/ZFAI06CC.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 422,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/2/4/e/8/24e8f9b6a7dd0013bb5edfe3a0efb30e.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZFAUUWZ9',
                title: 'Beast Mode',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/c/4/5/e/c45ef7c04e4926c5c3af108033fb5bd9.jpg',
                isoffical: true,
                link: '/album/Beast-Mode-Various-Artists/ZFAUUWZ9.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 422,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/c/4/5/e/c45ef7c04e4926c5c3af108033fb5bd9.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZOC0ZO9I',
                title: 'Motivation Mix',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/1/6/8/f/168fc2ef12ea08d76a8840f80647df0f.jpg',
                isoffical: true,
                link: '/album/Motivation-Mix-Various-Artists/ZOC0ZO9I.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 309,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/1/6/8/f/168fc2ef12ea08d76a8840f80647df0f.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
        ],
    },
    {
        encodeId: 'IWZ9Z09B',
        cover: 'https://photo-zmp3.zadn.vn/cover/9/4/5/2/94525d3e4dfd9b64b3cddb0365b00dcc.jpg',
        thumbnail: 'https://photo-zmp3.zadn.vn/cover/4/a/3/b/4a3b5265ee2c9e2c84f5a88194382b5d.jpg',
        thumbnailHasText: 'https://photo-zmp3.zadn.vn/cover/7/8/e/b/78eb333a7b7a350a03c7674c0613d04d.jpg',
        thumbnailR: 'https://photo-zmp3.zadn.vn/cover/3/e/2/5/3e25261cae8470995e8d88997e9c3e0e.jpg',
        title: 'Ngủ Ngon',
        link: '/hub/Ngu-Ngon/IWZ9Z09B.html',
        description: '',
        playlists: [
            {
                encodeId: 'ZOBIZWCB',
                title: 'Nghe Gì Dễ Ngủ?',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/d/3/e/0/d3e0a3515cb9307913defdf5822b9abb.jpg',
                isoffical: true,
                link: '/album/Nghe-Gi-De-Ngu-Various-Artists/ZOBIZWCB.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 298,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/d/3/e/0/d3e0a3515cb9307913defdf5822b9abb.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZOUZ07W7',
                title: 'Sleep Away',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/d/2/2/8/d228f4827cb623d3e6738dcb091afb35.jpg',
                isoffical: true,
                link: '/album/Sleep-Away-Various-Artists/ZOUZ07W7.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 234,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/d/2/2/8/d228f4827cb623d3e6738dcb091afb35.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZU6CO7ZW',
                title: 'Rap Việt Nghe Khi Đi Ngủ',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/0/e/0/7/0e0719ca475b7a50874c2de72c051af4.jpg',
                isoffical: true,
                link: '/album/Rap-Viet-Nghe-Khi-Di-Ngu-Various-Artists/ZU6CO7ZW.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 298,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/0/e/0/7/0e0719ca475b7a50874c2de72c051af4.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
        ],
    },
    {
        encodeId: 'IWZ9Z099',
        cover: 'https://photo-zmp3.zadn.vn/cover/9/5/e/2/95e21d554ae394322b3bb79f7a01617b.jpg',
        thumbnail: 'https://photo-zmp3.zadn.vn/cover/e/6/8/0/e680570f74b3497c95d96f6ba6db7b07.jpg',
        thumbnailHasText: 'https://photo-zmp3.zadn.vn/cover/4/f/d/a/4fda0068d6821c35e89a6d405b314ba0.jpg',
        thumbnailR: 'https://photo-zmp3.zadn.vn/cover/0/7/e/a/07eaa28ca48cc2557737deee06d3c3f6.jpg',
        title: 'Giai Điệu Buồn',
        link: '/hub/Giai-Dieu-Buon/IWZ9Z099.html',
        description: '',
        playlists: [
            {
                encodeId: 'ZOB8IU0I',
                title: 'Đi Rồi Mới Thương',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/0/7/8/5/0785a911741c0630f97fbb1b67065816.jpg',
                isoffical: true,
                link: '/album/Di-Roi-Moi-Thuong-Various-Artists/ZOB8IU0I.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 298,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/0/7/8/5/0785a911741c0630f97fbb1b67065816.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZOZ07WD8',
                title: "I'm Fine!",
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/0/0/0/1/0001f3e8570cbcab2a7788196e3e30bc.jpg',
                isoffical: true,
                link: '/album/I-m-Fine-Various-Artists/ZOZ07WD8.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 70,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/0/0/0/1/0001f3e8570cbcab2a7788196e3e30bc.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZOB66FIU',
                title: 'Những Mùa Nhớ Mong',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/a/9/9/8/a998954ee85582c4ff369744b3dbc28d.jpg',
                isoffical: true,
                link: '/album/Nhung-Mua-Nho-Mong-Various-Artists/ZOB66FIU.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 298,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/a/9/9/8/a998954ee85582c4ff369744b3dbc28d.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
        ],
    },
    {
        encodeId: 'IWZ9Z0AI',
        cover: 'https://photo-zmp3.zadn.vn/cover/d/f/b/2/dfb2357709d81574da689144f0348c78.jpg',
        thumbnail: 'https://photo-zmp3.zadn.vn/cover/b/1/e/b/b1eb8ae84392957f9b9d1ce2bb42aab9.jpg',
        thumbnailHasText: 'https://photo-zmp3.zadn.vn/cover/b/3/2/d/b32dab34664c9a7f0d1f837b4babd4bb.jpg',
        thumbnailR: 'https://photo-zmp3.zadn.vn/cover/3/f/3/2/3f3258892f1c047c566fddada2d18a10.jpg',
        title: 'Tập Trung',
        link: '/hub/Tap-Trung/IWZ9Z0AI.html',
        description: '',
        playlists: [
            {
                encodeId: '60BFCW79',
                title: 'Deep Concentration',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/8/8/a/1/88a1754544f5200a7cc6c573c9c1d97a.jpg',
                isoffical: true,
                link: '/album/Deep-Concentration-Various-Artists/60BFCW79.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 435,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/8/8/a/1/88a1754544f5200a7cc6c573c9c1d97a.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: '60BFAOA7',
                title: 'Focus Instrumental',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/2/8/4/0/28408bf16ae6fdb234107a25671c3cc2.jpg',
                isoffical: true,
                link: '/album/Focus-Instrumental-Various-Artists/60BFAOA7.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 435,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/2/8/4/0/28408bf16ae6fdb234107a25671c3cc2.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'S0BFCA0F',
                title: 'Classical Focus',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/5/c/2/6/5c268eb2511045a2a52c336bbda20514.jpg',
                isoffical: true,
                link: '/album/Classical-Focus-Various-Artists/S0BFCA0F.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 435,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/5/c/2/6/5c268eb2511045a2a52c336bbda20514.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
        ],
    },
    {
        encodeId: 'IWZ9Z0B6',
        cover: 'https://photo-zmp3.zadn.vn/cover/f/d/9/0/fd90bd3fabed951f29062bd0e5743078.jpg',
        thumbnail: 'https://photo-zmp3.zadn.vn/cover/8/5/d/1/85d1cfedf63d33e676e85071ab023f66.jpg',
        thumbnailHasText: 'https://photo-zmp3.zadn.vn/cover/0/b/4/c/0b4c68b2917b30138364a741147da057.jpg',
        thumbnailR: 'https://photo-zmp3.zadn.vn/cover/5/c/2/d/5c2da92cbc95016e8e588dacfd6980bf.jpg',
        title: 'Running',
        link: '/hub/Running/IWZ9Z0B6.html',
        description: '',
        playlists: [
            {
                encodeId: '6IID98BE',
                title: 'Daebak Run',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/d/7/3/5/d735e7295557229d82e59b5efe5ca841.jpg',
                isoffical: true,
                link: '/album/Daebak-Run-Various-Artists/6IID98BE.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 422,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/d/7/3/5/d735e7295557229d82e59b5efe5ca841.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: '6IIDC00O',
                title: 'Chạy Ngay Đi',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/0/3/5/7/0357a92e5d1feeccb8bf1704f40cb1d6.jpg',
                isoffical: true,
                link: '/album/Chay-Ngay-Di-Various-Artists/6IIDC00O.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 435,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/0/3/5/7/0357a92e5d1feeccb8bf1704f40cb1d6.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZOC0OZWA',
                title: 'Morning Run',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/0/e/7/d/0e7d58ad4b143401a3a83451f6c79156.jpg',
                isoffical: true,
                link: '/album/Morning-Run-Various-Artists/ZOC0OZWA.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 309,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/0/e/7/d/0e7d58ad4b143401a3a83451f6c79156.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
        ],
    },
    {
        encodeId: 'IWZ9Z09C',
        cover: 'https://photo-zmp3.zadn.vn/cover/1/3/d/a/13da957b7350667f92a0c6ae620c97ec.jpg',
        thumbnail: 'https://photo-zmp3.zadn.vn/cover/d/0/d/7/d0d772a6c3e35b3e768d5c3ebf644ecd.jpg',
        thumbnailHasText: 'https://photo-zmp3.zadn.vn/cover/8/7/d/c/87dc784f849a55fb343b0ed994a8d864.jpg',
        thumbnailR: 'https://photo-zmp3.zadn.vn/cover/4/7/8/0/47808cadd480844905b26104468e29b7.jpg',
        title: 'Spa - Yoga',
        link: '/hub/Spa-Yoga/IWZ9Z09C.html',
        description: '',
        playlists: [
            {
                encodeId: '6UCBA9UI',
                title: 'Spa Lounge',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/6/7/0/f/670f2846fbafcd6cac859fc35debaa98.jpg',
                isoffical: true,
                link: '/album/Spa-Lounge-Various-Artists/6UCBA9UI.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 457,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/6/7/0/f/670f2846fbafcd6cac859fc35debaa98.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: '6UBBBE9Z',
                title: 'Sounds Of Nature',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/f/f/0/c/ff0c7e32e0e2cb133839ab14cda1f377.jpg',
                isoffical: true,
                link: '/album/Sounds-Of-Nature-Various-Artists/6UBBBE9Z.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 457,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/f/f/0/c/ff0c7e32e0e2cb133839ab14cda1f377.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: '6UAEW80O',
                title: 'Namaste Yoga',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/f/5/5/4/f5544d2947e814adeb5bcf43cc767b68.jpg',
                isoffical: true,
                link: '/album/Namaste-Yoga-Various-Artists/6UAEW80O.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 457,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/f/5/5/4/f5544d2947e814adeb5bcf43cc767b68.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
        ],
    },
    {
        encodeId: 'IWZ9Z096',
        cover: 'https://photo-zmp3.zadn.vn/cover/f/b/7/9/fb79cd3242278a6d8f8a8e473a80cd3b.jpg',
        thumbnail: 'https://photo-zmp3.zadn.vn/cover/0/f/d/1/0fd1da7445b21a752a1c4282b06f2cf0.jpg',
        thumbnailHasText: 'https://photo-zmp3.zadn.vn/cover/a/2/7/8/a2784283efbab4c3b17e344f9b0a4b30.jpg',
        thumbnailR: 'https://photo-zmp3.zadn.vn/cover/9/2/2/d/922d20a7762e49a74a5564942189fb84.jpg',
        title: 'Thư Giãn',
        link: '/hub/Thu-Gian/IWZ9Z096.html',
        description: '',
        playlists: [
            {
                encodeId: 'ZOBF07ZB',
                title: 'EDM Thư Giãn Tốt Nhất',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/7/c/2/2/7c2268c10cdc1f15e2879670c5e94380.jpg',
                isoffical: true,
                link: '/album/EDM-Thu-Gian-Tot-Nhat-Various-Artists/ZOBF07ZB.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 309,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/7/c/2/2/7c2268c10cdc1f15e2879670c5e94380.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZWZCW7WZ',
                title: 'Giai Điệu Tropical Thư Giãn',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/8/e/0/9/8e09e708b537c466c77383864591fd04.jpg',
                isoffical: true,
                link: '/album/Giai-Dieu-Tropical-Thu-Gian-Various-Artists/ZWZCW7WZ.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 0,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/8/e/0/9/8e09e708b537c466c77383864591fd04.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZOUZOBFZ',
                title: 'Thư Giãn Cuối Tuần',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/a/2/0/5/a205073a584189de015e59f23e781483.jpg',
                isoffical: true,
                link: '/album/Thu-Gian-Cuoi-Tuan-Various-Artists/ZOUZOBFZ.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 235,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/a/2/0/5/a205073a584189de015e59f23e781483.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
        ],
    },
    {
        encodeId: 'IWZ9Z0CI',
        cover: 'https://photo-zmp3.zadn.vn/cover/d/6/2/1/d621f4cf5cecdf0ab58f6c4dfd8536a1.jpg',
        thumbnail: 'https://photo-zmp3.zadn.vn/cover/9/d/0/4/9d045c7d3a111975bb6920d963046dd1.jpg',
        thumbnailHasText: 'https://photo-zmp3.zadn.vn/cover/4/f/8/5/4f857e3277bb89b5e1c5ecc24598027c.jpg',
        thumbnailR: 'https://photo-zmp3.zadn.vn/cover/e/2/c/6/e2c683306586cb2e6e9cbfa77b4fd622.jpg',
        title: 'Chill',
        link: '/hub/Chill/IWZ9Z0CI.html',
        description: '',
        playlists: [
            {
                encodeId: '6IACDA86',
                title: 'Lo-fi Chút Thôi',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/a/8/d/e/a8de4d21ade258bb09ca9a52b34201a7.jpg',
                isoffical: true,
                link: '/album/Lo-fi-Chut-Thoi-Various-Artists/6IACDA86.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 457,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/a/8/d/e/a8de4d21ade258bb09ca9a52b34201a7.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZOUWE9EO',
                title: 'Acoustic Chill',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/2/a/8/f/2a8f1acf264c9c2ae309cce8e178b9d8.jpg',
                isoffical: true,
                link: '/album/Acoustic-Chill-Various-Artists/ZOUWE9EO.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 88,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/2/a/8/f/2a8f1acf264c9c2ae309cce8e178b9d8.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
            {
                encodeId: 'ZOCIIUWW',
                title: 'Chill Hits',
                thumbnail:
                    'https://photo-resize-zmp3.zadn.vn/w165_r1x1_jpeg/cover/a/5/c/d/a5cdfcc98a3368029781ff6bfa9b3abe.jpg',
                isoffical: true,
                link: '/album/Chill-Hits-Various-Artists/ZOCIIUWW.html',
                isIndie: false,
                PR: false,
                playItemMode: 0,
                subType: 1,
                uid: 309,
                thumbnailM:
                    'https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/cover/a/5/c/d/a5cdfcc98a3368029781ff6bfa9b3abe.jpg',
                isShuffle: true,
                isPrivate: false,
                userName: 'Zing MP3',
                isAlbum: false,
                textType: 'Playlist',
                isSingle: false,
            },
        ],
    },
]

function HAHA() {
    return <div></div>
}

export default HAHA
